//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClausesInitParameters) DeepCopyInto(out *ClausesInitParameters) {
	*out = *in
	if in.Attribute != nil {
		in, out := &in.Attribute, &out.Attribute
		*out = new(string)
		**out = **in
	}
	if in.ContextKind != nil {
		in, out := &in.ContextKind, &out.ContextKind
		*out = new(string)
		**out = **in
	}
	if in.Negate != nil {
		in, out := &in.Negate, &out.Negate
		*out = new(bool)
		**out = **in
	}
	if in.Op != nil {
		in, out := &in.Op, &out.Op
		*out = new(string)
		**out = **in
	}
	if in.ValueType != nil {
		in, out := &in.ValueType, &out.ValueType
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClausesInitParameters.
func (in *ClausesInitParameters) DeepCopy() *ClausesInitParameters {
	if in == nil {
		return nil
	}
	out := new(ClausesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClausesObservation) DeepCopyInto(out *ClausesObservation) {
	*out = *in
	if in.Attribute != nil {
		in, out := &in.Attribute, &out.Attribute
		*out = new(string)
		**out = **in
	}
	if in.ContextKind != nil {
		in, out := &in.ContextKind, &out.ContextKind
		*out = new(string)
		**out = **in
	}
	if in.Negate != nil {
		in, out := &in.Negate, &out.Negate
		*out = new(bool)
		**out = **in
	}
	if in.Op != nil {
		in, out := &in.Op, &out.Op
		*out = new(string)
		**out = **in
	}
	if in.ValueType != nil {
		in, out := &in.ValueType, &out.ValueType
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClausesObservation.
func (in *ClausesObservation) DeepCopy() *ClausesObservation {
	if in == nil {
		return nil
	}
	out := new(ClausesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClausesParameters) DeepCopyInto(out *ClausesParameters) {
	*out = *in
	if in.Attribute != nil {
		in, out := &in.Attribute, &out.Attribute
		*out = new(string)
		**out = **in
	}
	if in.ContextKind != nil {
		in, out := &in.ContextKind, &out.ContextKind
		*out = new(string)
		**out = **in
	}
	if in.Negate != nil {
		in, out := &in.Negate, &out.Negate
		*out = new(bool)
		**out = **in
	}
	if in.Op != nil {
		in, out := &in.Op, &out.Op
		*out = new(string)
		**out = **in
	}
	if in.ValueType != nil {
		in, out := &in.ValueType, &out.ValueType
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClausesParameters.
func (in *ClausesParameters) DeepCopy() *ClausesParameters {
	if in == nil {
		return nil
	}
	out := new(ClausesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSideAvailabilityInitParameters) DeepCopyInto(out *ClientSideAvailabilityInitParameters) {
	*out = *in
	if in.UsingEnvironmentID != nil {
		in, out := &in.UsingEnvironmentID, &out.UsingEnvironmentID
		*out = new(bool)
		**out = **in
	}
	if in.UsingMobileKey != nil {
		in, out := &in.UsingMobileKey, &out.UsingMobileKey
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSideAvailabilityInitParameters.
func (in *ClientSideAvailabilityInitParameters) DeepCopy() *ClientSideAvailabilityInitParameters {
	if in == nil {
		return nil
	}
	out := new(ClientSideAvailabilityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSideAvailabilityObservation) DeepCopyInto(out *ClientSideAvailabilityObservation) {
	*out = *in
	if in.UsingEnvironmentID != nil {
		in, out := &in.UsingEnvironmentID, &out.UsingEnvironmentID
		*out = new(bool)
		**out = **in
	}
	if in.UsingMobileKey != nil {
		in, out := &in.UsingMobileKey, &out.UsingMobileKey
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSideAvailabilityObservation.
func (in *ClientSideAvailabilityObservation) DeepCopy() *ClientSideAvailabilityObservation {
	if in == nil {
		return nil
	}
	out := new(ClientSideAvailabilityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSideAvailabilityParameters) DeepCopyInto(out *ClientSideAvailabilityParameters) {
	*out = *in
	if in.UsingEnvironmentID != nil {
		in, out := &in.UsingEnvironmentID, &out.UsingEnvironmentID
		*out = new(bool)
		**out = **in
	}
	if in.UsingMobileKey != nil {
		in, out := &in.UsingMobileKey, &out.UsingMobileKey
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSideAvailabilityParameters.
func (in *ClientSideAvailabilityParameters) DeepCopy() *ClientSideAvailabilityParameters {
	if in == nil {
		return nil
	}
	out := new(ClientSideAvailabilityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextTargetsInitParameters) DeepCopyInto(out *ContextTargetsInitParameters) {
	*out = *in
	if in.ContextKind != nil {
		in, out := &in.ContextKind, &out.ContextKind
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextTargetsInitParameters.
func (in *ContextTargetsInitParameters) DeepCopy() *ContextTargetsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ContextTargetsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextTargetsObservation) DeepCopyInto(out *ContextTargetsObservation) {
	*out = *in
	if in.ContextKind != nil {
		in, out := &in.ContextKind, &out.ContextKind
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextTargetsObservation.
func (in *ContextTargetsObservation) DeepCopy() *ContextTargetsObservation {
	if in == nil {
		return nil
	}
	out := new(ContextTargetsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextTargetsParameters) DeepCopyInto(out *ContextTargetsParameters) {
	*out = *in
	if in.ContextKind != nil {
		in, out := &in.ContextKind, &out.ContextKind
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextTargetsParameters.
func (in *ContextTargetsParameters) DeepCopy() *ContextTargetsParameters {
	if in == nil {
		return nil
	}
	out := new(ContextTargetsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPropertiesInitParameters) DeepCopyInto(out *CustomPropertiesInitParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPropertiesInitParameters.
func (in *CustomPropertiesInitParameters) DeepCopy() *CustomPropertiesInitParameters {
	if in == nil {
		return nil
	}
	out := new(CustomPropertiesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPropertiesObservation) DeepCopyInto(out *CustomPropertiesObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPropertiesObservation.
func (in *CustomPropertiesObservation) DeepCopy() *CustomPropertiesObservation {
	if in == nil {
		return nil
	}
	out := new(CustomPropertiesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPropertiesParameters) DeepCopyInto(out *CustomPropertiesParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPropertiesParameters.
func (in *CustomPropertiesParameters) DeepCopy() *CustomPropertiesParameters {
	if in == nil {
		return nil
	}
	out := new(CustomPropertiesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultsInitParameters) DeepCopyInto(out *DefaultsInitParameters) {
	*out = *in
	if in.OffVariation != nil {
		in, out := &in.OffVariation, &out.OffVariation
		*out = new(float64)
		**out = **in
	}
	if in.OnVariation != nil {
		in, out := &in.OnVariation, &out.OnVariation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultsInitParameters.
func (in *DefaultsInitParameters) DeepCopy() *DefaultsInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultsObservation) DeepCopyInto(out *DefaultsObservation) {
	*out = *in
	if in.OffVariation != nil {
		in, out := &in.OffVariation, &out.OffVariation
		*out = new(float64)
		**out = **in
	}
	if in.OnVariation != nil {
		in, out := &in.OnVariation, &out.OnVariation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultsObservation.
func (in *DefaultsObservation) DeepCopy() *DefaultsObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultsParameters) DeepCopyInto(out *DefaultsParameters) {
	*out = *in
	if in.OffVariation != nil {
		in, out := &in.OffVariation, &out.OffVariation
		*out = new(float64)
		**out = **in
	}
	if in.OnVariation != nil {
		in, out := &in.OnVariation, &out.OnVariation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultsParameters.
func (in *DefaultsParameters) DeepCopy() *DefaultsParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallthroughInitParameters) DeepCopyInto(out *FallthroughInitParameters) {
	*out = *in
	if in.BucketBy != nil {
		in, out := &in.BucketBy, &out.BucketBy
		*out = new(string)
		**out = **in
	}
	if in.ContextKind != nil {
		in, out := &in.ContextKind, &out.ContextKind
		*out = new(string)
		**out = **in
	}
	if in.RolloutWeights != nil {
		in, out := &in.RolloutWeights, &out.RolloutWeights
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallthroughInitParameters.
func (in *FallthroughInitParameters) DeepCopy() *FallthroughInitParameters {
	if in == nil {
		return nil
	}
	out := new(FallthroughInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallthroughObservation) DeepCopyInto(out *FallthroughObservation) {
	*out = *in
	if in.BucketBy != nil {
		in, out := &in.BucketBy, &out.BucketBy
		*out = new(string)
		**out = **in
	}
	if in.ContextKind != nil {
		in, out := &in.ContextKind, &out.ContextKind
		*out = new(string)
		**out = **in
	}
	if in.RolloutWeights != nil {
		in, out := &in.RolloutWeights, &out.RolloutWeights
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallthroughObservation.
func (in *FallthroughObservation) DeepCopy() *FallthroughObservation {
	if in == nil {
		return nil
	}
	out := new(FallthroughObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallthroughParameters) DeepCopyInto(out *FallthroughParameters) {
	*out = *in
	if in.BucketBy != nil {
		in, out := &in.BucketBy, &out.BucketBy
		*out = new(string)
		**out = **in
	}
	if in.ContextKind != nil {
		in, out := &in.ContextKind, &out.ContextKind
		*out = new(string)
		**out = **in
	}
	if in.RolloutWeights != nil {
		in, out := &in.RolloutWeights, &out.RolloutWeights
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallthroughParameters.
func (in *FallthroughParameters) DeepCopy() *FallthroughParameters {
	if in == nil {
		return nil
	}
	out := new(FallthroughParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlag) DeepCopyInto(out *FeatureFlag) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlag.
func (in *FeatureFlag) DeepCopy() *FeatureFlag {
	if in == nil {
		return nil
	}
	out := new(FeatureFlag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeatureFlag) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagEnvironment) DeepCopyInto(out *FeatureFlagEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagEnvironment.
func (in *FeatureFlagEnvironment) DeepCopy() *FeatureFlagEnvironment {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeatureFlagEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagEnvironmentInitParameters) DeepCopyInto(out *FeatureFlagEnvironmentInitParameters) {
	*out = *in
	if in.ContextTargets != nil {
		in, out := &in.ContextTargets, &out.ContextTargets
		*out = make([]ContextTargetsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvKey != nil {
		in, out := &in.EnvKey, &out.EnvKey
		*out = new(string)
		**out = **in
	}
	if in.Fallthrough != nil {
		in, out := &in.Fallthrough, &out.Fallthrough
		*out = make([]FallthroughInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FlagID != nil {
		in, out := &in.FlagID, &out.FlagID
		*out = new(string)
		**out = **in
	}
	if in.OffVariation != nil {
		in, out := &in.OffVariation, &out.OffVariation
		*out = new(float64)
		**out = **in
	}
	if in.On != nil {
		in, out := &in.On, &out.On
		*out = new(bool)
		**out = **in
	}
	if in.Prerequisites != nil {
		in, out := &in.Prerequisites, &out.Prerequisites
		*out = make([]PrerequisitesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]RulesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrackEvents != nil {
		in, out := &in.TrackEvents, &out.TrackEvents
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagEnvironmentInitParameters.
func (in *FeatureFlagEnvironmentInitParameters) DeepCopy() *FeatureFlagEnvironmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagEnvironmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagEnvironmentList) DeepCopyInto(out *FeatureFlagEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FeatureFlagEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagEnvironmentList.
func (in *FeatureFlagEnvironmentList) DeepCopy() *FeatureFlagEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeatureFlagEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagEnvironmentObservation) DeepCopyInto(out *FeatureFlagEnvironmentObservation) {
	*out = *in
	if in.ContextTargets != nil {
		in, out := &in.ContextTargets, &out.ContextTargets
		*out = make([]ContextTargetsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvKey != nil {
		in, out := &in.EnvKey, &out.EnvKey
		*out = new(string)
		**out = **in
	}
	if in.Fallthrough != nil {
		in, out := &in.Fallthrough, &out.Fallthrough
		*out = make([]FallthroughObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FlagID != nil {
		in, out := &in.FlagID, &out.FlagID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.OffVariation != nil {
		in, out := &in.OffVariation, &out.OffVariation
		*out = new(float64)
		**out = **in
	}
	if in.On != nil {
		in, out := &in.On, &out.On
		*out = new(bool)
		**out = **in
	}
	if in.Prerequisites != nil {
		in, out := &in.Prerequisites, &out.Prerequisites
		*out = make([]PrerequisitesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]RulesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrackEvents != nil {
		in, out := &in.TrackEvents, &out.TrackEvents
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagEnvironmentObservation.
func (in *FeatureFlagEnvironmentObservation) DeepCopy() *FeatureFlagEnvironmentObservation {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagEnvironmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagEnvironmentParameters) DeepCopyInto(out *FeatureFlagEnvironmentParameters) {
	*out = *in
	if in.ContextTargets != nil {
		in, out := &in.ContextTargets, &out.ContextTargets
		*out = make([]ContextTargetsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvKey != nil {
		in, out := &in.EnvKey, &out.EnvKey
		*out = new(string)
		**out = **in
	}
	if in.Fallthrough != nil {
		in, out := &in.Fallthrough, &out.Fallthrough
		*out = make([]FallthroughParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FlagID != nil {
		in, out := &in.FlagID, &out.FlagID
		*out = new(string)
		**out = **in
	}
	if in.OffVariation != nil {
		in, out := &in.OffVariation, &out.OffVariation
		*out = new(float64)
		**out = **in
	}
	if in.On != nil {
		in, out := &in.On, &out.On
		*out = new(bool)
		**out = **in
	}
	if in.Prerequisites != nil {
		in, out := &in.Prerequisites, &out.Prerequisites
		*out = make([]PrerequisitesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]RulesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrackEvents != nil {
		in, out := &in.TrackEvents, &out.TrackEvents
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagEnvironmentParameters.
func (in *FeatureFlagEnvironmentParameters) DeepCopy() *FeatureFlagEnvironmentParameters {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagEnvironmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagEnvironmentSpec) DeepCopyInto(out *FeatureFlagEnvironmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagEnvironmentSpec.
func (in *FeatureFlagEnvironmentSpec) DeepCopy() *FeatureFlagEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagEnvironmentStatus) DeepCopyInto(out *FeatureFlagEnvironmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagEnvironmentStatus.
func (in *FeatureFlagEnvironmentStatus) DeepCopy() *FeatureFlagEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagInitParameters) DeepCopyInto(out *FeatureFlagInitParameters) {
	*out = *in
	if in.Archived != nil {
		in, out := &in.Archived, &out.Archived
		*out = new(bool)
		**out = **in
	}
	if in.ClientSideAvailability != nil {
		in, out := &in.ClientSideAvailability, &out.ClientSideAvailability
		*out = make([]ClientSideAvailabilityInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomProperties != nil {
		in, out := &in.CustomProperties, &out.CustomProperties
		*out = make([]CustomPropertiesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = make([]DefaultsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.MaintainerID != nil {
		in, out := &in.MaintainerID, &out.MaintainerID
		*out = new(string)
		**out = **in
	}
	if in.MaintainerTeamKey != nil {
		in, out := &in.MaintainerTeamKey, &out.MaintainerTeamKey
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectKey != nil {
		in, out := &in.ProjectKey, &out.ProjectKey
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Temporary != nil {
		in, out := &in.Temporary, &out.Temporary
		*out = new(bool)
		**out = **in
	}
	if in.VariationType != nil {
		in, out := &in.VariationType, &out.VariationType
		*out = new(string)
		**out = **in
	}
	if in.Variations != nil {
		in, out := &in.Variations, &out.Variations
		*out = make([]VariationsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagInitParameters.
func (in *FeatureFlagInitParameters) DeepCopy() *FeatureFlagInitParameters {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagList) DeepCopyInto(out *FeatureFlagList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FeatureFlag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagList.
func (in *FeatureFlagList) DeepCopy() *FeatureFlagList {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeatureFlagList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagObservation) DeepCopyInto(out *FeatureFlagObservation) {
	*out = *in
	if in.Archived != nil {
		in, out := &in.Archived, &out.Archived
		*out = new(bool)
		**out = **in
	}
	if in.ClientSideAvailability != nil {
		in, out := &in.ClientSideAvailability, &out.ClientSideAvailability
		*out = make([]ClientSideAvailabilityObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomProperties != nil {
		in, out := &in.CustomProperties, &out.CustomProperties
		*out = make([]CustomPropertiesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = make([]DefaultsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.MaintainerID != nil {
		in, out := &in.MaintainerID, &out.MaintainerID
		*out = new(string)
		**out = **in
	}
	if in.MaintainerTeamKey != nil {
		in, out := &in.MaintainerTeamKey, &out.MaintainerTeamKey
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectKey != nil {
		in, out := &in.ProjectKey, &out.ProjectKey
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Temporary != nil {
		in, out := &in.Temporary, &out.Temporary
		*out = new(bool)
		**out = **in
	}
	if in.VariationType != nil {
		in, out := &in.VariationType, &out.VariationType
		*out = new(string)
		**out = **in
	}
	if in.Variations != nil {
		in, out := &in.Variations, &out.Variations
		*out = make([]VariationsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagObservation.
func (in *FeatureFlagObservation) DeepCopy() *FeatureFlagObservation {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagParameters) DeepCopyInto(out *FeatureFlagParameters) {
	*out = *in
	if in.Archived != nil {
		in, out := &in.Archived, &out.Archived
		*out = new(bool)
		**out = **in
	}
	if in.ClientSideAvailability != nil {
		in, out := &in.ClientSideAvailability, &out.ClientSideAvailability
		*out = make([]ClientSideAvailabilityParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomProperties != nil {
		in, out := &in.CustomProperties, &out.CustomProperties
		*out = make([]CustomPropertiesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = make([]DefaultsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.MaintainerID != nil {
		in, out := &in.MaintainerID, &out.MaintainerID
		*out = new(string)
		**out = **in
	}
	if in.MaintainerTeamKey != nil {
		in, out := &in.MaintainerTeamKey, &out.MaintainerTeamKey
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectKey != nil {
		in, out := &in.ProjectKey, &out.ProjectKey
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Temporary != nil {
		in, out := &in.Temporary, &out.Temporary
		*out = new(bool)
		**out = **in
	}
	if in.VariationType != nil {
		in, out := &in.VariationType, &out.VariationType
		*out = new(string)
		**out = **in
	}
	if in.Variations != nil {
		in, out := &in.Variations, &out.Variations
		*out = make([]VariationsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagParameters.
func (in *FeatureFlagParameters) DeepCopy() *FeatureFlagParameters {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagSpec) DeepCopyInto(out *FeatureFlagSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagSpec.
func (in *FeatureFlagSpec) DeepCopy() *FeatureFlagSpec {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagStatus) DeepCopyInto(out *FeatureFlagStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagStatus.
func (in *FeatureFlagStatus) DeepCopy() *FeatureFlagStatus {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrerequisitesInitParameters) DeepCopyInto(out *PrerequisitesInitParameters) {
	*out = *in
	if in.FlagKey != nil {
		in, out := &in.FlagKey, &out.FlagKey
		*out = new(string)
		**out = **in
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrerequisitesInitParameters.
func (in *PrerequisitesInitParameters) DeepCopy() *PrerequisitesInitParameters {
	if in == nil {
		return nil
	}
	out := new(PrerequisitesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrerequisitesObservation) DeepCopyInto(out *PrerequisitesObservation) {
	*out = *in
	if in.FlagKey != nil {
		in, out := &in.FlagKey, &out.FlagKey
		*out = new(string)
		**out = **in
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrerequisitesObservation.
func (in *PrerequisitesObservation) DeepCopy() *PrerequisitesObservation {
	if in == nil {
		return nil
	}
	out := new(PrerequisitesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrerequisitesParameters) DeepCopyInto(out *PrerequisitesParameters) {
	*out = *in
	if in.FlagKey != nil {
		in, out := &in.FlagKey, &out.FlagKey
		*out = new(string)
		**out = **in
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrerequisitesParameters.
func (in *PrerequisitesParameters) DeepCopy() *PrerequisitesParameters {
	if in == nil {
		return nil
	}
	out := new(PrerequisitesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesInitParameters) DeepCopyInto(out *RulesInitParameters) {
	*out = *in
	if in.BucketBy != nil {
		in, out := &in.BucketBy, &out.BucketBy
		*out = new(string)
		**out = **in
	}
	if in.Clauses != nil {
		in, out := &in.Clauses, &out.Clauses
		*out = make([]ClausesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContextKind != nil {
		in, out := &in.ContextKind, &out.ContextKind
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.RolloutWeights != nil {
		in, out := &in.RolloutWeights, &out.RolloutWeights
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesInitParameters.
func (in *RulesInitParameters) DeepCopy() *RulesInitParameters {
	if in == nil {
		return nil
	}
	out := new(RulesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesObservation) DeepCopyInto(out *RulesObservation) {
	*out = *in
	if in.BucketBy != nil {
		in, out := &in.BucketBy, &out.BucketBy
		*out = new(string)
		**out = **in
	}
	if in.Clauses != nil {
		in, out := &in.Clauses, &out.Clauses
		*out = make([]ClausesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContextKind != nil {
		in, out := &in.ContextKind, &out.ContextKind
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.RolloutWeights != nil {
		in, out := &in.RolloutWeights, &out.RolloutWeights
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesObservation.
func (in *RulesObservation) DeepCopy() *RulesObservation {
	if in == nil {
		return nil
	}
	out := new(RulesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesParameters) DeepCopyInto(out *RulesParameters) {
	*out = *in
	if in.BucketBy != nil {
		in, out := &in.BucketBy, &out.BucketBy
		*out = new(string)
		**out = **in
	}
	if in.Clauses != nil {
		in, out := &in.Clauses, &out.Clauses
		*out = make([]ClausesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContextKind != nil {
		in, out := &in.ContextKind, &out.ContextKind
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.RolloutWeights != nil {
		in, out := &in.RolloutWeights, &out.RolloutWeights
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesParameters.
func (in *RulesParameters) DeepCopy() *RulesParameters {
	if in == nil {
		return nil
	}
	out := new(RulesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetsInitParameters) DeepCopyInto(out *TargetsInitParameters) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetsInitParameters.
func (in *TargetsInitParameters) DeepCopy() *TargetsInitParameters {
	if in == nil {
		return nil
	}
	out := new(TargetsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetsObservation) DeepCopyInto(out *TargetsObservation) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetsObservation.
func (in *TargetsObservation) DeepCopy() *TargetsObservation {
	if in == nil {
		return nil
	}
	out := new(TargetsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetsParameters) DeepCopyInto(out *TargetsParameters) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Variation != nil {
		in, out := &in.Variation, &out.Variation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetsParameters.
func (in *TargetsParameters) DeepCopy() *TargetsParameters {
	if in == nil {
		return nil
	}
	out := new(TargetsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariationsInitParameters) DeepCopyInto(out *VariationsInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariationsInitParameters.
func (in *VariationsInitParameters) DeepCopy() *VariationsInitParameters {
	if in == nil {
		return nil
	}
	out := new(VariationsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariationsObservation) DeepCopyInto(out *VariationsObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariationsObservation.
func (in *VariationsObservation) DeepCopy() *VariationsObservation {
	if in == nil {
		return nil
	}
	out := new(VariationsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariationsParameters) DeepCopyInto(out *VariationsParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariationsParameters.
func (in *VariationsParameters) DeepCopy() *VariationsParameters {
	if in == nil {
		return nil
	}
	out := new(VariationsParameters)
	in.DeepCopyInto(out)
	return out
}
