apiVersion: project.launchdarkly.com/v1alpha1
kind: EnvironmentSegment
metadata:
  name: example-segment
spec:
  forProvider:
    description: This segment is managed by Crossplane
    projectKey: crossplane-project
    envKey: test
    includedContexts:
      - contextKind: account
        values:
          - account1
          - account2
    key: example-segment-key
    name: example segment

    rules:
      - clauses:
          - attribute: country
            contextKind: location-data
            negate: false
            op: startsWith
            values:
              - en
              - de
              - un
      - clauses:
          - attribute: country
            contextKind: location-data
            negate: false
            op: startsWith
            values:
              - tok
        rolloutContextKind: location-data
        weight: 50000

    tags:
      - segment-tag-1
      - segment-tag-2
