// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AccessToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuditLogSubscription) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CustomRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Team) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TeamMember) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TeamRoleMapping) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Webhook) Hub() {}
