apiVersion: account.launchdarkly.com/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: account/v1alpha1/team
  labels:
    testing.upbound.io/example-name: platform_team
  name: platform-team
spec:
  forProvider:
    customRoleKeysRefs:
    - name: example
    - name: example
    description: Team to manage internal infrastructure
    key: platform_team
    maintainersRefs:
    - name: example
    memberIdsRefs:
    - name: example
    - name: example
    name: Platform team
